--Part 1
-- Id (INT), Name (VARCHAR), EmployerId (INT)
--Part 2
--SELECT Name FROM techjobs.employers;
--Part 3
--SELECT	Name, Description
--FROM techjobs.skills, techjobs.jobskills
--WHERE techjobs.jobskills.SkillId = techjobs.skills.Id
--ORDER BY Name ASC;
